TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_vel_theta: 0.3
  min_vel_theta: 0.1
  min_in_place_vel_theta: 0.25

  acc_lim_theta: 2.0
  acc_lim_x: 2.0
  acc_lim_Y: 2.0

  holonomic_robot: true

  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25